collecti_stamp/base/urls.py
from django.urls import path

from .views import home

urlpatterns = [
    path('', home, name='home'),
]

collecti_stamp/collecti_stamp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('base.urls')),
    path('catalog/', include('catalog.urls')),
    path('claim/', include('claim.urls')),
    path('company/', include('company.urls')),
    path('customer/', include('customer.urls')),
    path('order/', include('order.urls')),
    path('postorder/', include('postorder.urls')),
    path('preorder/', include('preorder.urls')),
    path('product/', include('product.urls')),
]

collecti_stamp/postorder/urls.py
from django.urls import path

from postorder.views import get_order_tracking,list_order_tracking,get_order_tracking_finder


urlpatterns = [
    path('<uuid:code>', get_order_tracking, name='order_details'),
    path('my_orders/',list_order_tracking, name='my_orders'),
    path('',get_order_tracking_finder,name='finder_order')
]

collecti_stamp/order/models.py
import uuid

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from product.models import *


class PaymentMethod(models.TextChoices):
    CASH_ON_DELIVERY = 'CASH_ON_DELIVERY', 'Contrarrembolso'
    PAYMENT_GATEWAY = 'PAYPAL', 'PayPal'


class DeliveryStatus(models.TextChoices):
    IN_WAREHOUSE = 'IN_WAREHOUSE', 'En almacén'
    ON_THE_WAY = 'ON_THE_WAY', 'En camino'
    DELIVERED = 'DELIVERED', 'Entregado'


class DeliveryMethod(models.TextChoices):
    STANDARD_SHIPPING = 'STANDARD_SHIPPING', 'Envío estándar (2.99 €)'
    EXPRESS_SHIPPING = 'EXPRESS_SHIPPING', 'Envío express (4.99 €)'
    PICKUP_IN_STORE = 'PICKUP_IN_STORE', 'Recogida en tienda (0.00 €)'


class Order(models.Model):
    id = models.AutoField(primary_key=True)
    code = models.UUIDField(default=uuid.uuid4, editable=False)
    user_email = models.EmailField()
    user_name = models.CharField(max_length=50)
    order_date = models.DateField()
    order_total = models.DecimalField(max_digits=7, decimal_places=2)
    order_is_finished = models.BooleanField(default=False)
    payment_method = models.CharField(max_length=20, choices=PaymentMethod.choices)
    delivery_status = models.CharField(max_length=20, choices=DeliveryStatus.choices)
    delivery_method = models.CharField(max_length=20, choices=DeliveryMethod.choices)
    delivery_cost = models.DecimalField(max_digits=7, decimal_places=2)
    delivery_address = models.TextField(max_length=500)

    class Meta:
        verbose_name = "Compra"
        verbose_name_plural = "Compras"

    def __str__(self):
        return "Compra " + str(self.id)


class OrderProduct(models.Model):
    id = models.AutoField(primary_key=True)
    order_id = models.ManyToManyField(Order)
    product_id = models.ManyToManyField(Product)
    quantity = models.IntegerField(validators=[
            MinValueValidator(limit_value=0, message='La cantidad no puede ser negativa.'),
            MaxValueValidator(limit_value=999, message='La cantidad no puede ser mayor que 999.'),
    ])

    class Meta:
        verbose_name = "Producto de compra"
        verbose_name_plural = "Productos de compra"

collecti_stamp/postorder/models.py
# Create your models here.

collecti_stamp/postorder/views.py
import re

from base.views import home
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_http_methods
from order.models import Order


# Create your views here.
def get_order_tracking(request, code):  # Change the parameter name
    order = get_object_or_404(Order, code=code)
    state_name = {
        'IN_WAREHOUSE': 'En almacén',
        'ON_THE_WAY': 'En camino',
        'DELIVERED': 'Entregado',
    }
    delivery_methods = {
        'STANDARD_SHIPPING': 'Envío estándar',
        'EXPRESS_SHIPPING': 'Envío express',
        'PICKUP_IN_STORE': 'Recogida en tienda',
    }
    payment_methods = {
        'CASH_ON_DELIVERY': 'Contrarrembolso',
        'PAYPAL': 'PayPal',
    } 
    state=state_name.get(order.delivery_status)
    delivery_method=delivery_methods.get(order.delivery_method)
    payment_method=payment_methods.get(order.payment_method)
    return render(request, 'postorder/order_details.html', {'order': order, 'state':state,'delivery_method':delivery_method,'payment_method':payment_method})

@require_http_methods(["GET"])
def get_order_tracking_finder(request):  # Change the parameter name
    code = request.GET.get('code')
    guiones= re.sub(r'[^-]', '', code)
    if (len(code) == 36) and (len(guiones)==4) and (Order.objects.filter(code=code).count()>0):
        order= Order.objects.filter(code=code).first()
        state_name = {
            'IN_WAREHOUSE': 'En almacén',
            'ON_THE_WAY': 'En camino',
            'DELIVERED': 'Entregado',
        }
        delivery_methods = {
            'STANDARD_SHIPPING': 'Envío estándar',
            'EXPRESS_SHIPPING': 'Envío express',
            'PICKUP_IN_STORE': 'Recogida en tienda',
        }
        payment_methods = {
            'CASH_ON_DELIVERY': 'Contrarrembolso',
            'PAYPAL': 'PayPal',
        } 
        state=state_name.get(order.delivery_status)
        delivery_method=delivery_methods.get(order.delivery_method)
        payment_method=payment_methods.get(order.payment_method)
        return render(request, 'postorder/order_details.html', {'order': order, 'state':state,'delivery_method':delivery_method,'payment_method':payment_method})
    else:
        return home(request)
    
@login_required
def list_order_tracking(request):
    orders = Order.objects.filter(user_email=request.user.email)
    return render(request, 'postorder/order_list.html', {'orders': orders})

collecti_stamp/templates/postorder/finder_order.html
<div class="container">
    <div class="row">
        <div class="col-md-6 search">
            <form method="get" action="{% url 'finder_order' %}">
                <div id="custom-search-input" class="input-group">
                    <input type="text" name="code" id="query" value="{{ request.GET.code }}" class="form-control"
                           placeholder="Rastree su pedido"/>
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-success">
                            <i class="icon icon-search"></i> Buscar
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

collecti_stamp/templates/postorder/order_details.html
{% extends "base.html" %}

{% block title %}Inicio de Sesión{% endblock %}
{% block content %}
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #343a40;
            margin: 0;
            padding: 0;
        }

        .container2 {
            display: flex;
            width: 80%;
            margin: 20px auto;
            background-color: #fff;
            border: 1px solid #ddd;
            border-radius: 5px;
            overflow: hidden;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .left-half {
            flex: 1;
            padding: 20px;
            border-right: 1px solid #ddd;
            text-align: center;
        }

        .left-half img {
            max-width: 100%;
            height: auto;
            border-radius: 5px;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
        }

        .left-half .description-box {
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 10px;
            margin-top: 20px;
            text-align: left;
        }

        .left-half label {
            display: block;
            margin-top: 10px;
            font-size: 1.2em;
            color: #333;
        }


        .left-half button {
            padding: 15px 10px;
            background-color: #343a40;
            color: white;
            border: none;
            border-radius: 3px;
            cursor: pointer;
            font-size: 1.2em;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .left-half button:hover {
            background-color: #000000;
        }

        .right-half {
            flex: 1;
            padding: 20px;
        }

        h1 {
            color: #333;
            font-size: 2em;
            font-weight: bold;
        }

        p {
            margin-bottom: 10px;
        }

        strong {
            color: #444aa0;
            font-weight: bold;
            font-size: 1.2em;
        }

        .attribute {
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
            margin-bottom: 10px;
        }

        .criteria-box {
            display: inline-block;
            padding: 5px 7px;
            margin: 0 3px 3px 0;
            background-color: #343a40;
            color: white;
            border-radius: 2px;
        }    
    </style>

    <div class="container2">
        <div class="right-half">
            <p class="attribute"><strong>Estado:</strong> {{ state }}</p>
            <p class="attribute"><strong>Usuario:</strong> {{ order.user_name }}</p>
            <p class="attribute"><strong>Email:</strong> {{ order.user_email }}</p>
            <p class="attribute"><strong>Dirección:</strong> {{ order.delivery_address }}</p>
            <p class="attribute"><strong>Fecha de Pedido:</strong> {{ order.order_date }}</p>
            <p class="attribute"><strong>Método de Pago :</strong> {{ payment_method }}</p>
            <p class="attribute"><strong>Método de Envío :</strong> {{ delivery_method }}</p>
            <p class="attribute"><strong>Coste Productos:</strong> {{ order.order_total }}</p>
            <p class="attribute"><strong>Coste envío:</strong> {{ order.delivery_cost }}</p>
            <p class="attribute"><strong>Código:</strong> {{ order.code }}</p>
        </div>
    </div>

{% endblock %}

collecti_stamp/templates/postorder/order_list.html
{% extends "base.html" %}

{% block title %}
    Mis pedidos
{% endblock %}

{% block content %}
    <style>
        /* Estilo para la columna "#" */
        .table-bordered th:first-child {
            background-color: #343a40; /* Color de fondo gris oscuro */
            color: #fff; /* Color del texto blanco */
        }

        /* Estilo para la frase "Lista de Pedidos" */
        .page-title {
            color: #007BFF; /* Color del texto blanco */
            padding: 10px; /* Añadir espacio alrededor del texto para mayor legibilidad */
            margin-bottom: 20px; /* Añadir espacio debajo del título */
        }

        /* Quitar el efecto de hover */
        .table-hover tbody tr:hover {
            background-color: inherit; /* Mantener el color de fondo original */
        }
    </style>

    <div class="container mt-5">
        <h2 class="text-center mb-4 page-title">Lista de Pedidos</h2>

        <!-- Tabla de pedidos para admin-->
        <div class="table-responsive">
            <table class="table table-bordered table-hover">
                <caption>Lista de pedidos realizados por el usuario.</caption>
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        {% if request.user.is_superuser %}
                            <th scope="col">Usuario</th>
                            <th scope="col">Código</th>
                        {% endif %}
                        <th scope="col">Fecha de pedido</th>
                        <th scope="col">Coste</th>
                        <th scope="col">Método de pago</th>
                        <th scope="col">Método de envío</th>
                        <th scope="col">Dirección de envío</th>
                        <th scope="col">Estado</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        {% if request.user.is_superuser %}
                            <td>{{ order.user_name }}</td>
                            <td>{{ order.code }}</td>
                        {% endif %}
                        <td>{{ order.order_date }}</td>
                        <td>{{ order.order_total }}€</td>
                        <td>{{ order.get_payment_method_display }}</td>
                        <td>{{ order.get_delivery_method_display }}</td>
                        <td>{{ order.delivery_address }}</td>
                        <td>{{ order.get_delivery_status_display }}</td>
                        <td>
                            <!-- Enlace a la página de detalles con el ID del pedido como parámetro -->
                            <a href="{% url 'order_details' order.code %}" class="btn btn-sm btn-primary">Detalles</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}