collecti_stamp/base/urls.py
from django.urls import path

from .views import home

urlpatterns = [
    path('', home, name='home'),
]

collecti_stamp/collecti_stamp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('base.urls')),
    path('catalog/', include('catalog.urls')),
    path('claim/', include('claim.urls')),
    path('company/', include('company.urls')),
    path('customer/', include('customer.urls')),
    path('order/', include('order.urls')),
    path('postorder/', include('postorder.urls')),
    path('preorder/', include('preorder.urls')),
    path('product/', include('product.urls')),
]

collecti_stamp/order/urls.py
from django.urls import path

from .views import finish_order, PurchaseStep1View, PurchaseStep2View, PurchaseStep3View, PayPalPaymentView, \
    PayPalSuccesView, PayPalCancelView

app_name = 'order'

urlpatterns = [
    path('finish/', finish_order, name='finish_order'),
    path('finish/<int:new_order_id>/step1/', PurchaseStep1View.as_view(), name='purchase_step1'),
    path('finish/<int:new_order_id>/step2/', PurchaseStep2View.as_view(), name='purchase_step2'),
    path('finish/<int:new_order_id>/step3/', PurchaseStep3View.as_view(), name='purchase_step3'),
    path('create-payment/<int:order_id>/', PayPalPaymentView.as_view(), name='create_payment'),
    path('payment/success/', PayPalSuccesView.as_view(), name='payment_success'),
    path('payment/cancel/', PayPalCancelView.as_view(), name='payment_cancel'),
]

collecti_stamp/order/models.py
import uuid

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from product.models import *


class PaymentMethod(models.TextChoices):
    CASH_ON_DELIVERY = 'CASH_ON_DELIVERY', 'Contrarrembolso'
    PAYMENT_GATEWAY = 'PAYPAL', 'PayPal'


class DeliveryStatus(models.TextChoices):
    IN_WAREHOUSE = 'IN_WAREHOUSE', 'En almacén'
    ON_THE_WAY = 'ON_THE_WAY', 'En camino'
    DELIVERED = 'DELIVERED', 'Entregado'


class DeliveryMethod(models.TextChoices):
    STANDARD_SHIPPING = 'STANDARD_SHIPPING', 'Envío estándar (2.99 €)'
    EXPRESS_SHIPPING = 'EXPRESS_SHIPPING', 'Envío express (4.99 €)'
    PICKUP_IN_STORE = 'PICKUP_IN_STORE', 'Recogida en tienda (0.00 €)'


class Order(models.Model):
    id = models.AutoField(primary_key=True)
    code = models.UUIDField(default=uuid.uuid4, editable=False)
    user_email = models.EmailField()
    user_name = models.CharField(max_length=50)
    order_date = models.DateField()
    order_total = models.DecimalField(max_digits=7, decimal_places=2)
    order_is_finished = models.BooleanField(default=False)
    payment_method = models.CharField(max_length=20, choices=PaymentMethod.choices)
    delivery_status = models.CharField(max_length=20, choices=DeliveryStatus.choices)
    delivery_method = models.CharField(max_length=20, choices=DeliveryMethod.choices)
    delivery_cost = models.DecimalField(max_digits=7, decimal_places=2)
    delivery_address = models.TextField(max_length=500)

    class Meta:
        verbose_name = "Compra"
        verbose_name_plural = "Compras"

    def __str__(self):
        return "Compra " + str(self.id)


class OrderProduct(models.Model):
    id = models.AutoField(primary_key=True)
    order_id = models.ManyToManyField(Order)
    product_id = models.ManyToManyField(Product)
    quantity = models.IntegerField(validators=[
            MinValueValidator(limit_value=0, message='La cantidad no puede ser negativa.'),
            MaxValueValidator(limit_value=999, message='La cantidad no puede ser mayor que 999.'),
    ])

    class Meta:
        verbose_name = "Producto de compra"
        verbose_name_plural = "Productos de compra"

collecti_stamp/order/forms.py
from django import forms

from .models import DeliveryMethod, PaymentMethod


class CustomerDataForm(forms.Form):
    user_name = forms.CharField(max_length=100, required=True)
    delivery_address = forms.CharField(max_length=250, required=True)
    user_email = forms.EmailField(required=True)
    

class DeliveryMethodSelection(forms.Form):
    default_choice = 'default'
    delivery_method = forms.ChoiceField(
        choices=[(default_choice, 'Selecciona un método de entrega')] + list(DeliveryMethod.choices),
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'}),
        error_messages={'required': 'Este campo es requerido.'}
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['delivery_method'].label = 'Método de Entrega'

    def clean_delivery_method(self):
        delivery_method = self.cleaned_data['delivery_method']
        if delivery_method == self.default_choice:
            raise forms.ValidationError("Por favor, selecciona un método de entrega válido.")
        return delivery_method


class PaymentMethodForm(forms.Form):
    default_choice = 'default'
    payment_method = forms.ChoiceField(
        choices=[(default_choice, 'Selecciona un método de pago')] + list(PaymentMethod.choices),
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'}),
        error_messages={'required': 'Este campo es requerido.'}
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Establecer etiqueta y texto de ayuda en español
        self.fields['payment_method'].label = 'Método de Pago'
        self.fields['payment_method'].help_text = 'Selecciona un método de pago'

    def clean_payment_method(self):
        payment_method = self.cleaned_data['payment_method']
        if payment_method == self.default_choice:
            raise forms.ValidationError("Por favor, selecciona un método de pago válido.")
        return payment_method

    def add_error(self, field, error):
        if field == '__all__':
            error = "Por favor, completa el formulario correctamente."
        super().add_error(field, error)

collecti_stamp/order/views.py
from datetime import date, datetime

import paypalrestsdk
from decouple import config
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import get_object_or_404, render, redirect
from django.template.loader import get_template
from django.urls import reverse
from django.views import View
from django.views.decorators.http import require_http_methods
from paypalrestsdk import Payment
from preorder.cart import Cart
from preorder.context_processor import total_cart
from product.models import Product

from .forms import CustomerDataForm, DeliveryMethodSelection, PaymentMethodForm
from .models import Order, OrderProduct, PaymentMethod, DeliveryMethod, DeliveryStatus


@require_http_methods(["POST"])
def finish_order(request):
    new_order = Order.objects.create(
        user_email="",
        order_date=date.today(),
        order_total=total_cart(request).get("total_cart", 0),
        order_is_finished=False,
        payment_method='',
        delivery_status='',
        delivery_method='',
        delivery_cost=0,
        delivery_address='',
    )
    new_order.save()
    new_order_id = new_order.id
    cart = request.session['cart']
    for product_id, product_info in cart.items():
        order_product = OrderProduct.objects.create(
            quantity=product_info['amount']
        )
        order_product.order_id.set([new_order])
        order_product.product_id.set([product_id])
        order_product.save()

    return redirect(str(new_order_id)+"/step1/")

class PurchaseStep1View(View):
    template_name = 'order/purchase_step1.html'

    def get(self, request, new_order_id):
        order_products = OrderProduct.objects.filter(order_id=new_order_id)
        payment_methods = PaymentMethod.choices
        user_is_logged_in = request.user.is_authenticated
        form = PaymentMethodForm(request.POST)
        products = get_order_products(order_products)
        order = get_object_or_404(Order, id=new_order_id) 
        return render(request, self.template_name,
               {
                'order_products': order_products,
                'payment_methods': payment_methods,
                'order_id': new_order_id,
                'form': form, 'products': products,
                'user_is_logged_in': user_is_logged_in,
                'order_total': order.order_total
                })

    def post(self, request, new_order_id):

        form = PaymentMethodForm(request.POST)
        if form.is_valid():
            order = get_object_or_404(Order, id=new_order_id)
            order.payment_method = form.cleaned_data['payment_method']
            order.save()
            return redirect('order:purchase_step2', new_order_id=new_order_id)

        order_products = OrderProduct.objects.filter(order_id=new_order_id)
        payment_methods = PaymentMethod.choices
        user_is_logged_in = request.user.is_authenticated
        form = PaymentMethodForm(request.POST)
        products = get_order_products(order_products)
        order = get_object_or_404(Order, id=new_order_id) 
        return render(request, self.template_name,
               {
                'order_products': order_products,
                'payment_methods': payment_methods,
                'order_id': new_order_id,
                'form': form, 'products': products,
                'user_is_logged_in': user_is_logged_in,
                'order_total': order.order_total
                })
        
        
class PurchaseStep2View(View):
    template_name = 'order/purchase_step2.html'
    
    def get(self, request, new_order_id):
        order_products = OrderProduct.objects.filter(order_id=new_order_id)
        delivery_method = DeliveryMethod.choices
        user_is_logged_in = request.user.is_authenticated
        form = DeliveryMethodSelection(request.POST)
        products = get_order_products(order_products)
        order = get_object_or_404(Order, id=new_order_id) 
        return render(request, self.template_name,
               {
                'order_products': order_products,
                'delivery_method': delivery_method,
                'order_id': new_order_id,
                'form': form,
                'products': products,
                'user_is_logged_in': user_is_logged_in,
                'order_total': order.order_total
                })
        
    def post(self, request, new_order_id):
        form = DeliveryMethodSelection(request.POST)
        if form.is_valid():
            order = get_object_or_404(Order, id=new_order_id)
            order.delivery_method = form.cleaned_data['delivery_method']
            
            delivery_cost = 0.0
            if order.delivery_method == DeliveryMethod.STANDARD_SHIPPING and order.order_total < 50:
                delivery_cost = 2.99
            elif order.delivery_method == DeliveryMethod.EXPRESS_SHIPPING and order.order_total < 50:
                delivery_cost = 4.99
            order.delivery_cost = delivery_cost
            
            order.save()
            return redirect('order:purchase_step3', new_order_id=new_order_id)
        order_products = OrderProduct.objects.filter(order_id=new_order_id)
        delivery_method = DeliveryMethod.choices
        user_is_logged_in = request.user.is_authenticated
        form = DeliveryMethodSelection(request.POST)
        products = get_order_products(order_products)
        order = get_object_or_404(Order, id=new_order_id) 
        return render(request, self.template_name,
               {
                'order_products': order_products,
                'delivery_method': delivery_method,
                'order_id': new_order_id,
                'form': form, 'products': products,
                'user_is_logged_in': user_is_logged_in,
                'order_total': order.order_total
                })


class PurchaseStep3View(View):
    template_name = 'order/purchase_step3.html'

    def get(self, request, new_order_id):
        order_products = OrderProduct.objects.filter(order_id=new_order_id)
        payment_methods = PaymentMethod.choices
        user_is_logged_in = request.user.is_authenticated
        
        order = get_object_or_404(Order, id=new_order_id)
        delivery_cost = order.delivery_cost
        cost = delivery_cost + order.order_total

        form = CustomerDataForm()
        products = get_order_products(order_products)

        return render(request, self.template_name, {
            'order_products': order_products,
            'payment_methods': payment_methods,
            'new_order_id': new_order_id,
            'delivery_cost': delivery_cost,
            'customer_form': form,
            'products': products,
            'user_is_logged_in': user_is_logged_in,
            'cost':cost,
        })

    def post(self, request, new_order_id):
        customer_form = CustomerDataForm(request.POST)

        if customer_form.is_valid():
            order = get_object_or_404(Order, id=new_order_id)
            order.user_email = customer_form.cleaned_data['user_email']
            order.user_name = customer_form.cleaned_data['user_name']
            order.delivery_address = customer_form.cleaned_data['delivery_address']
            order.delivery_status = DeliveryStatus.IN_WAREHOUSE
            order.order_is_finished = True
            order.delivery_date = datetime.now()
            order_products = OrderProduct.objects.filter(order_id=new_order_id)

            for order_product in order_products:
                product = get_object_or_404(Product, id=order_product.product_id.first().id)
                if product.stock_amount < order_product.quantity:
                    return redirect('/?message=Uno de los productos se ha agotado&status=Error')

                product.stock_amount -= order_product.quantity
                product.save()

            order.save()
            details_url = reverse('order_details', args=[order.code])
            
            cart = Cart(request)
            cart.delete_cart()

            # Enviar el correo electrónico de verificación
            template = get_template('order/email_details.html')
            content = template.render(
                {'details_url': request.build_absolute_uri('/') + details_url, 'order': order, 'order_products': order_products})
            message = EmailMultiAlternatives(
                'Detalles de compra',
                content,
                settings.EMAIL_HOST_USER,
                [order.user_email]
            )

            message.attach_alternative(content, 'text/html')
            message.send()
            
            if(order.payment_method=="PAYPAL"):
                return redirect('order:create_payment', order_id=order.id)
            else:
                return redirect('/?message=Compra Realizada&status=Success')

        order_products = OrderProduct.objects.filter(order_id=new_order_id)
        payment_methods = PaymentMethod.choices
        user_is_logged_in = request.user.is_authenticated

        form = customer_form
        products = get_order_products(order_products)

        return render(request, self.template_name, {
            'order_products': order_products,
            'payment_methods': payment_methods,
            'new_order_id': new_order_id,
            'customer_form': form,
            'products': products,
            'user_is_logged_in': user_is_logged_in,
        })

def get_order_products(order_products):
    products = []
    for order_product in order_products:
        product = get_object_or_404(Product, id=order_product.product_id.first().id)
        products.append(product)
    return products

class PayPalPaymentView(View):
    def get(self, request, order_id):
        paypalrestsdk.configure({
            "mode": "sandbox",  # sandbox or live
            "client_id": config('PAYPAL_CLIENT_ID'),
            "client_secret": config('PAYPAL_CLIENT_SECRET')
        })

collecti_stamp/templates/order/purchase_step1.html
{% extends "base.html" %}

{% block title %}Confirmación de Compra - Paso 1{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2 class="text-center text-primary mb-4">Confirmación de Compra - Paso 1</h2>

        <div class="row justify-content-center">
            <div class="col-md-8 bg-white rounded shadow p-4">
                <h3 class="text-center text-dark mb-4">Productos Comprados</h3>
                <ul class="list-group">
                    {% for product in products %}
                        <li class="list-group-item bg-light border-0">
                            {{ product.name }} {{ product.quantity }} - Precio por unidad: {{ product.price }} €
                        </li>
                    {% endfor %}
                </ul>

                <!-- Etiqueta movida fuera del formulario -->
                <h3 class="mt-4 text-center text-dark mb-3">Selecciona un Método de Pago</h3>

                <form method="post">
                    {% csrf_token %}

                    <!-- Aviso de campo requerido más pequeño -->
                    <div class="form-group">
                        {{ form.payment_method.label_tag }}
                        {{ form.payment_method }}
                        <small class="form-text text-muted">Este campo es requerido.</small>
                    </div>

                    <div class="text-center button-container mt-4">
                        <button type="button" class="btn btn-danger" id="previous-btn" onclick="goToPreviousStep()">Cancelar Compra</button>
                        {% if user_is_logged_in %}
                            <button type="button" class="btn btn-success" id="auto-fill-btn" onclick="autoFillData()">Mi Método Favorito</button>
                        {% endif %}
                        <button type="submit" class="btn btn-primary" id="next-btn">Ir al Siguiente Paso</button>
                    </div>
                </form>

                <div class="warning mt-4 text-center bg-light rounded shadow p-4">
                    <p class="text-muted">
                        Por favor, ten en cuenta que las devoluciones no están permitidas.
                    </p>
                </div>
            </div>
        </div>
    </div>

    <script>
        function goToPreviousStep() {
            window.location.href = '/catalog/';
        }

        function autoFillData() {
            var payment_method = "{{ request.user.payment_method }}";
            document.getElementById('id_payment_method').value = payment_method ;
        }
    </script>
{% endblock %}

collecti_stamp/templates/order/purchase_step2.html
{% extends "base.html" %}

{% block title %}Confirmación de Compra - Paso 2{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2 class="text-center text-primary mb-4">Confirmación de Compra - Paso 2</h2>

        <div class="row justify-content-center">
            <div class="col-md-8 bg-white rounded shadow p-4">
                <h3 class="text-center text-dark mb-4">Productos Comprados</h3>
                <ul class="list-group">
                    {% for product in products %}
                        <li class="list-group-item bg-light border-0">
                            {{ product.name }} {{ product.quantity }} - Precio por unidad: {{ product.price }} €
                        </li>
                    {% endfor %}
                </ul>

                <h3 class="mt-4 text-center text-dark mb-3">Selecciona Método de Entrega</h3>

                <form method="post">
                    {% csrf_token %}

                    <div class="form-group">
                        {{ form.delivery_method.label_tag }}
                        {{ form.delivery_method }}
                        <small id="delivery-method-error" class="form-text text-muted">Este campo es requerido.</small>
                    </div>

                    <div class="text-center button-container mt-4">
                        <button type="button" class="btn btn-danger" id="previous-btn" onclick="goToPreviousStep()">Ir al Paso Anterior</button>
                        {% if user_is_logged_in %}
                            <button type="button" class="btn btn-success" id="auto-fill-btn" onclick="autoFillData()">Mi Método Favorito</button>
                        {% endif %}
                        <button type="submit" class="btn btn-primary" id="next-btn">Ir al Siguiente Paso</button>
                    </div>
                </form>

                <div class="warning mt-4 text-center bg-light rounded shadow p-4">
                    <p class="text-muted">
                        El precio de los gastos de envío es de 0€ en los pedidos de más de 50€.
                    </p>
                    <p class="text-muted">
                        Por favor, ten en cuenta que no se admiten devoluciones.
                    </p>
                </div>
            </div>
        </div>
    </div>

    <script>
        function goToPreviousStep() {
            var previousStepUrl = '/order/finish/{{ order_id }}/step1/';
            window.location.href = previousStepUrl;
        }

        function autoFillData() {
            var delivery_method = "{{ request.user.delivery_method }}";
            document.getElementById('id_delivery_method').value = delivery_method;
        }

        // Función para manejar la validación del formulario antes de enviarlo
        document.querySelector('form').addEventListener('submit', function (event) {
            var deliveryMethodError = document.getElementById('delivery-method-error');
            var deliveryMethodField = document.getElementById('id_delivery_method');

            // Validación del campo de método de entrega
            if (!deliveryMethodField.value) {
                deliveryMethodError.textContent = 'Este campo es requerido.';
                event.preventDefault();  // Evita que el formulario se envíe si hay errores
            } else {
                deliveryMethodError.textContent = '';  // Limpia el mensaje si el campo es válido
            }
        });
    </script>
{% endblock %}

collecti_stamp/templates/order/purchase_step3.html
{% extends "base.html" %}

{% block title %}Confirmación de Compra - Paso 3{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2 class="text-center text-primary mb-4">Confirmación de Compra - Paso 3</h2>

        <div class="row justify-content-center">
            <div class="col-md-8 bg-white rounded shadow p-4">
                <h3 class="text-center text-dark mb-4">Productos Comprados</h3>
                <ul class="list-group">
                    {% for product in products %}
                        <li class="list-group-item bg-light border-0">
                            {{ product.name }} {{ product.quantity }} - Precio por unidad: {{ product.price }} €
                        </li>
                    {% endfor %}
                </ul>
                <br>
                <div class="list-group">
                    <p class="list-group-item">Gastos de envío: {{ delivery_cost }} €</p>
                </div>
                <div class="list-group">
                    <p class="list-group-item" style="font-weight: bold;">Total del pedido: {{ cost }} €</p>
                </div>
                <h3 class="mt-4 text-center text-dark mb-3">Introducir datos</h3>
                <form method="post" style="width: 60%; margin: 20px auto; padding: 20px; background-color: #ffffff; border-radius: 10px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); text-align: center;">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_user_name" style="display: block; margin-bottom: 8px; color: #333;">Nombre:</label>
                        <input type="text" name="user_name" id="id_user_name" class="form-control" placeholder="Ingrese su nombre" required>
                        <small class="form-text text-muted">Este campo es requerido.</small>
                    </div>
                    <div class="form-group">
                        <label for="id_delivery_address" style="display: block; margin-bottom: 8px; color: #333;">Dirección de Envío:</label>
                        <input type="text" name="delivery_address" id="id_delivery_address" class="form-control" placeholder="Ingrese su dirección de envío" required>
                        <small class="form-text text-muted">Este campo es requerido.</small>
                    </div>
                    <div class="form-group">
                        <label for="id_user_email" style="display: block; margin-bottom: 8px; color: #333;">Correo Electrónico:</label>
                        <input type="email" name="user_email" id="id_user_email" class="form-control" placeholder="Ingrese su correo electrónico" required>
                        <small class="form-text text-muted">Este campo es requerido.</small>
                    </div>
                    <div class="text-center button-container mt-4">
                        <button type="button" class="btn" id="previous-btn" onclick="goToPreviousStep()" style="background-color: #dc3545; color: #ffffff; margin-top: 10px; border: none; margin-right: 10px;">Ir al Paso Anterior</button>
                        {% if user_is_logged_in %}
                            <button type="button" class="btn" id="auto-fill-btn" onclick="autoFillData()" style="background-color: #28a745; color: #ffffff; margin-top: 10px; border: none; margin-right: 10px;">Rellenar Automáticamente</button>
                        {% endif %}
                        <button type="submit" class="btn btn-primary" id="next-btn" style="background-color: #007bff; color: #ffffff; margin-top: 10px; border: none;">Finalizar Compra</button>
                    </div>
                </form>
                <div class="warning mt-4 text-center bg-light rounded shadow p-4">
                    <p class="text-muted">Por favor, tenga en cuenta que no se admiten devoluciones.</p>
                </div>
            </div>
        </div>
    </div>

    <script>
        function goToPreviousStep() {
            var order_id = '{{ new_order_id }}';
            var previousStepUrl = '/order/finish/' + order_id + '/step2/';
            window.location.href = previousStepUrl;
        }

        function autoFillData() {
            var user_name = "{{ request.user.username }}";
            var delivery_address = "{{ request.user.address|default:'' }}";  // Usar cadena vacía si es None
            var user_email = "{{ request.user.email }}";

            document.getElementById('id_user_name').value = user_name || '';
            document.getElementById('id_delivery_address').value = delivery_address || '';
            document.getElementById('id_user_email').value = user_email || '';
        }
    </script>
{% endblock %}