collecti_stamp/base/urls.py
from django.urls import path

from .views import home

urlpatterns = [
    path('', home, name='home'),
]

collecti_stamp/collecti_stamp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('base.urls')),
    path('catalog/', include('catalog.urls')),
    path('claim/', include('claim.urls')),
    path('company/', include('company.urls')),
    path('customer/', include('customer.urls')),
    path('order/', include('order.urls')),
    path('postorder/', include('postorder.urls')),
    path('preorder/', include('preorder.urls')),
    path('product/', include('product.urls')),
]

collecti_stamp/product/urls.py
from django.urls import path

from .views import ProductDetailsView

urlpatterns = [
    path('product/<int:product_id>/', ProductDetailsView.as_view(), name='product_details'),
]

collecti_stamp/product/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


class Category(models.TextChoices):

    ANCIENT = 'ANCIENT', 'Antiguo'
    COMIC_BOOK = 'COMIC_BOOK', 'Comic'
    VIDEOGAME = 'VIDEOGAME', 'Videojuego'
    HISTORICAL = 'HISTORICAL', 'Histórico'
    NOVELTY = 'NOVELTY', 'Novedad'


class Criteria(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40)

    class Meta:
        verbose_name = "Criterio"
        verbose_name_plural = "Criterios"

    def __str__(self):
        return self.name


class ProductType(models.TextChoices):
    COIN = 'COIN', 'Moneda'
    SEAL = 'SEAL', 'Sello'


class Product(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    stock_amount = models.IntegerField(validators=[
            MinValueValidator(limit_value=0, message='La cantidad no puede ser negativa.'),
            MaxValueValidator(limit_value=999, message='La cantidad no puede ser mayor que 999.'),
    ])
    product_type = models.CharField(max_length=10, choices=ProductType.choices)
    category = models.CharField(max_length=15, choices=Category.choices)
    criteria = models.ManyToManyField(Criteria)
    image = models.ImageField(upload_to='static/img/product/')

    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"

    def __str__(self):
        return self.name

class ProductReview(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=100, default="Anónimo")
    name = models.CharField(max_length=100, default="Reseña sin título")
    description = models.TextField(max_length=500)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Reseña"
        verbose_name_plural = "Reseñas"

    def __str__(self):
        return self.name

collecti_stamp/product/forms.py
# forms.py
from django import forms

from .models import ProductReview


class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = ProductReview
        fields = ['username', 'name', 'description']
        labels = {
            'username': 'Autor de la reseña',
            'name': 'Título de la reseña',
            'description': 'Descripción',
        }

collecti_stamp/product/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.views.decorators.http import require_http_methods

from .forms import ProductReviewForm
from .models import Criteria
from .models import Product
from .models import ProductReview


class ProductDetailsView(View):
    template_name = 'product/details.html'

    def get(self, request, product_id):
        product = get_object_or_404(Product, pk=product_id)
        form = ProductReviewForm()
        return render(request, self.template_name, {'product': product, 'form': form})

    def post(self, request, product_id):
        product = get_object_or_404(Product, pk=product_id)
        form = ProductReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.product = product
            review.save()
            return redirect('product_details', product_id=product_id)

        return render(request, self.template_name, {'product': product, 'form': form})

@require_http_methods(["GET"])
def product_catalog(request):
    products = Product.objects.all()
    criteria = Criteria.objects.all()

    criteria1 = request.GET.get('criteria1')
    criteria2 = request.GET.get('criteria2')
    criteria3 = request.GET.get('criteria3')

    if criteria1:
        products = products.filter(criteria__id=criteria1)
    if criteria2:
        products = products.filter(criteria__id=criteria2)
    if criteria3:
        products = products.filter(criteria__id=criteria3)

    reviews = ProductReview.objects.filter(product=1)

    return render(request, 'product/product_catalog.html', {'products': products, 'criteria': criteria, reviews: reviews})

collecti_stamp/templates/product/details.html
{% extends "base.html" %}

{% block title %}Inicio de Sesión{% endblock %}

{% block content %}
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #343a40;
            margin: 0;
            padding: 0;
        }

        .container2 {
            display: flex;
            width: 80%;
            margin: 20px auto;
            background-color: #fff;
            border: 1px solid #ddd;
            border-radius: 5px;
            overflow: hidden;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .left-half {
            flex: 1;
            padding: 20px;
            border-right: 1px solid #ddd;
            text-align: center;
        }

        .left-half img {
            max-width: 100%;
            height: auto;
            border-radius: 5px;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
        }

        .left-half .description-box {
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 10px;
            margin-top: 20px;
            text-align: left;
        }

        .left-half label {
            display: block;
            margin-top: 10px;
            font-size: 1.2em;
            color: #333;
        }


        .left-half button {
            padding: 15px 10px;
            background-color: #343a40;
            color: white;
            border: none;
            border-radius: 3px;
            cursor: pointer;
            font-size: 1.2em;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .left-half button:hover {
            background-color: #000000;
        }

        .right-half {
            flex: 1;
            padding: 20px;
        }

        h1 {
            color: #333;
            font-size: 2em;
            font-weight: bold;
        }

        p {
            margin-bottom: 10px;
        }

        strong {
            color: #444aa0;
            font-weight: bold;
            font-size: 1.2em;
        }

        .attribute {
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
            margin-bottom: 10px;
        }

        .criteria-box {
            display: inline-block;
            padding: 5px 7px;
            margin: 0 3px 3px 0;
            background-color: #343a40;
            color: white;
            border-radius: 2px;
        }
        .reviews-section {
            margin-top: 20px;
        }

        .reviews-list {
            list-style: none;
            padding: 0;
        }

        .review-item {
            border: 1px solid #ddd;
            border-radius: 5px;
            margin-bottom: 15px;
            padding: 15px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .review-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 10px;
        }

        .review-header strong {
            font-size: 1.2em;
        }

        .review-date {
            font-size: 0.9em;
            color: #777;
        }

        .review-description {
            font-size: 1em;
            line-height: 1.4;
        }

        .no-reviews {
            font-style: italic;
            color: #777;
        }


        .add-review-section {
            margin-top: 20px;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 8px;
            background-color: #f9f9f9;
        }

        .add-review-section h2 {
            color: #333;
            font-size: 1.5em;
        }

        .add-review-section form {
            margin-top: 15px;
        }

        .add-review-section label {
            display: block;
            margin-bottom: 8px;
            font-weight: bold;
        }

        .add-review-section input[type="text"],
        .add-review-section textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        .add-review-section button {
            background-color: #007BFF;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        .add-review-section button:hover {
            background-color: #0056b3;
        }
        .overlay-image {
            position: absolute;
            top: 23rem;
            left: 33rem;
            width: 21%;
            height: 21.5%;
        }
        .claim {
            background-color: #007BFF;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        
        .claim:hover {
            background-color: #0056b3;
        }

    </style>

    <div class="container2">
        <div class="left-half">
            {% if product.image %}
                <img src="{{ product.image.url }}" alt="{{ product.name }}">
                {% if product.stock_amount <= 0 %}
                    <img class="overlay-image" src="/static/img/out_of_stock.png" alt="Imagen Superpuesta">
                {% endif %}
            {% else %}
                <img src="static/img/product/placeholder-image.jpg" alt="{{ product.name }}">
            {% endif %}
            <div class="description-box">

                <label for="quantity"><strong>Cantidad a comprar:</strong></label>
                {% include "product/input_quantity.html" with max=product.stock_amount %}
            </div>
        </div>

        <div class="right-half">
            <h1>{{ product.name }}</h1>
            <p class="attribute"><span style="font-size: 2.5em;">{{ product.price }} €</span></p>
            <p class="attribute"><strong>Tipo de Producto:</strong> {{ product.get_product_type_display }}</p>
            <p class="attribute"><strong>Cantidad disponible en stock:</strong> {{ product.stock_amount }}</p>
            <p class="attribute"><strong>Categoría:</strong> {{ product.get_category_display }}</p>

            <p class="attribute"><strong>Etiquetas:</strong>
                {% for criteria in product.criteria.all %}
                    <span class="criteria-box">{{ criteria.name }}</span>
                {% endfor %}
            </p>
            {% include "product/expand_text.html" with title="Descripción" description=product.description %}
        </div>
    </div>

<div class="reviews-section">
    <div class="add-review-section">
        <h2>Añadir Reseña</h2>
        <form method="post" action="{% url 'product_details' product.id %}">
                {% csrf_token %}
                {{ form.as_p }}
            <button type="submit">Añadir Reseña</button>
        </form>
    </div>
    <h1>Reseñas del Producto</h1>
    {% if product.productreview_set.all %}
        <ul class="reviews-list">
            {% for review in product.productreview_set.all %}
                <li class="review-item">
                    <div class="review-header">
                        <strong>{{ review.username }}</strong>
                        <p class="review-date">Fecha: {{ review.date }}</p>
                    </div>
                    <p class="review-name">{{ review.name }}</p>
                    <p class="review-description">{{ review.description }}</p>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p class="no-reviews">No hay reseñas para este producto.</p>
    {% endif %}
</div>
<a href="{% url 'create_claim' product.id %}">
    <button class="claim-deez-nuts">Poner Reclamación</button>
</a>

{% endblock %}

collecti_stamp/templates/product/expand_text.html
<style>

    .fa-chevron-down:hover {
        color: #1bbeb4;
    }

    .fa-chevron-up:hover {
        color: #1bbeb4;
    }


    .hidden {
        display: none;
    }

    .container-description {
        display: flex;
        flex-direction: column;
        border-bottom: 1px solid #e4e4e4;
        padding: 10px 0;
    }

    .title-description {
        display: flex;
        align-items: center;
        justify-content: space-between;
        cursor: pointer;
    }

    .title-description h4 {
        font-weight: 300;
        color: #666;
        font-size: 14px;
    }

    .text-description {
        font-size: 13px;
        color: #252525;
        line-height: 22px;
        margin-top: 25px;
    }


</style>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Toggle
// Constantes Toggle Titles
        const toggleDescription = document.querySelector(
            '.title-description'
        );
// Constantes Contenido Texto
        const contentDescription = document.querySelector(
            '.text-description'
        );
// Funciones Toggle
        toggleDescription.addEventListener('click', () => {
            contentDescription.classList.toggle('hidden');
        });
    });

</script>
<script src="https://kit.fontawesome.com/81581fb069.js" crossorigin="anonymous"></script>
<div class="container-description">
    <div class="title-description">
        <strong>{{ title }}</strong>
        <i class="fa-solid fa-chevron-down"></i>
    </div>
    <div class="text-description">
        <p>
            {{ description }}
        </p>
    </div>
</div>

collecti_stamp/templates/product/input_quantity.html
<style>

    .container-add-cart {
        display: flex;
        gap: 20px;
        padding-bottom: 30px;
        border-bottom: 1px solid #e4e4e4;
    }

    .container-quantity {
        position: relative;
    }

    .input-quantity::-webkit-inner-spin-button,
    .input-quantity::-webkit-outer-spin-button,
    .input-quantity {
        -webkit-appearance: none;
        margin: 0;
    }

    .input-quantity {
        -moz-appearance: textfield;
        background-color: #f7f7f7;
        border: none;
        padding: 10px;
        width: 60px;
        color: #666;
        font-weight: 500;
    }

    .input-quantity:focus {
        outline: none;
    }

    .btn-increment-decrement {
        display: flex;
        flex-direction: column;
        position: absolute;
        top: 15px;
        right: 7px;
    }

    .btn-increment-decrement i {
        font-size: 11px;
        color: #666;
        cursor: pointer;
    }

    .fa-chevron-down:hover {
        color: #1bbeb4;
    }

    .fa-chevron-up:hover {
        color: #1bbeb4;
    }

    .btn-add-to-cart {
        border: none;
        background-color: #252525;
        padding: 10px;
        color: #f7f7f7;
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 5px;
        font-weight: 700;
        cursor: pointer;
    }

    .btn-add-to-cart:hover {
        color: #1bbeb4;
    }

    .hidden {
        display: none;
    }

</style>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const inputQuantity = document.querySelector('.input-quantity');
        const btnIncrement = document.querySelector('#increment');
        const btnDecrement = document.querySelector('#decrement');
        const amount = document.querySelector('#amount');

        let valueByDefault = parseInt(inputQuantity.value);

        btnIncrement.addEventListener('click', () => {
            if (valueByDefault === parseInt(inputQuantity.max)) {
                return;
            }
            valueByDefault += 1;
            inputQuantity.value = valueByDefault;
            let link = amount.href.split('/');
            link[link.length - 2] = valueByDefault;
            amount.href = link.join('/');
        });

        btnDecrement.addEventListener('click', () => {
            if (valueByDefault === 1) {
                return;
            }
            valueByDefault -= 1;
            inputQuantity.value = valueByDefault;
            let link = amount.href.split('/');
            link[link.length - 2] = valueByDefault;
            amount.href = link.join('/');
        });
    });
</script>

<script
        src="https://kit.fontawesome.com/81581fb069.js"
        crossorigin="anonymous"
></script>
<div class="container-add-cart">
    <div class="container-quantity">
        <input
                type="number"
                placeholder="1"
                value="1"
                min="1"
                max="{{ max }}"
                class="input-quantity"
        />
        <div class="btn-increment-decrement">
            <i class="fa-solid fa-chevron-up" id="increment"></i>
            <i class="fa-solid fa-chevron-down" id="decrement"></i>
        </div>
    </div>
    <button class="btn-add-to-cart">
        <i class="fa-solid fa-plus"></i>
        <a href={% url 'add_product' product.id 1 %} id="amount-{{ product.id }}" class="btn btn-primary">Añadir</a>
    </button>
</div>

collecti_stamp/templates/product/input_quantity_mini.html
<style>
    .container-add-cart {
        display: flex;
        gap: 20px;
        padding-bottom: 30px;
        border-bottom: 1px solid #e4e4e4;
    }

    .container-quantity {
        position: relative;
    }

    .input-quantity::-webkit-inner-spin-button,
    .input-quantity::-webkit-outer-spin-button,
    .input-quantity {
        -webkit-appearance: none;
        margin: 0;
    }

    .input-quantity {
        -moz-appearance: textfield;
        background-color: #f7f7f7;
        border: none;
        padding: 10px;
        width: 60px;
        color: #666;
        font-weight: 500;
    }

    .input-quantity:focus {
        outline: none;
    }

    .btn-increment-decrement {
        position: absolute;
        top: 50%;
        transform: translateY(-50%);
        right: 7px;
        display: flex;
        flex-direction: column;
    }

    .btn-increment-decrement i {
        font-size: 11px;
        color: #666;
        cursor: pointer;
    }

    .fa-chevron-down:hover,
    .fa-chevron-up:hover {
        color: #1bbeb4;
    }

    .btn-add-to-cart {
        border: none;
        background-color: #252525;
        padding: 5px; /* Aún más pequeño el padding */
        color: #f7f7f7;
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 5px;
        font-weight: 700;
        cursor: pointer;
    }

    .btn-add-to-cart:hover {
        color: #1bbeb4;
    }

    .hidden {
        display: none;
    }
</style>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const inputQuantity = document.querySelectorAll('#input-quantity-{{ product.id }}');
        const btnIncrement = document.querySelectorAll('#increment-{{ product.id }}');
        const btnDecrement = document.querySelectorAll('#decrement-{{ product.id }}');
        const amounts = document.querySelectorAll('#amount-{{ product.id }}');

        // Iterar sobre todos los elementos seleccionados
        inputQuantity.forEach(function (input) {
            let valueByDefault = parseInt(input.value);

            btnIncrement.forEach(function (btn, index) {
                btn.addEventListener('click', () => {
                    if (valueByDefault === parseInt(input.max)) {
                        return;
                    }
                    valueByDefault += 1;
                    input.value = valueByDefault;
                    let link = amounts[index].href.split("/");
                    link[link.length - 2] = valueByDefault;
                    console.log(link);
                    amounts[index].href = link.join("/");
                });
            });

            btnDecrement.forEach(function (btn, index) {
                btn.addEventListener('click', () => {
                    if (valueByDefault === 1) {
                        return;
                    }
                    valueByDefault -= 1;
                    input.value = valueByDefault;
                    let link = amounts[index].href.split("/");
                    link[link.length - 2] = valueByDefault;
                    amounts[index].href = link.join("/");
                });
            });
        });
    });
</script>
<script src="https://kit.fontawesome.com/81581fb069.js" crossorigin="anonymous"></script>
<div class="container-add-cart">
    <div class="container-quantity">
        <input type="number" placeholder="1" value="1" min="1" max="{{ max }}" class="input-quantity" id="input-quantity-{{ product.id }}"/>
        <div class="btn-increment-decrement">
            <i class="fa-solid fa-chevron-up" id="increment-{{ product.id }}"></i>
            <i class="fa-solid fa-chevron-down" id="decrement-{{ product.id }}"></i>
        </div>
    </div>
    <button class="btn-add-to-cart">
        <i class="fa-solid fa-plus"></i>
        <a href={% url 'add_product' product.id 1 %} id="amount-{{ product.id }}" class="btn btn-primary">Añadir</a>
    </button>
</div>

collecti_stamp/templates/product/out_of_stock.html
<style>
    .container3 {
        position: relative;
        width: 12rem; /* Ancho de la imagen base */
    }

    .overlay-image {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }

    img.catalog-image {
        max-width: 100%;
        max-height: 150px;
        border-radius: 8px;
        margin-bottom: 10px;
    }
</style>

<body>
<div class="container3">
    <img src="{{ base_path }}" alt="Imagen Base" class="catalog-image">
    {% if stock_amount <= 0 %}
        <img class="overlay-image" src="{{ overlay_path }}" alt="Imagen Superpuesta">
    {% endif %}
</div>
</body>

collecti_stamp/templates/product/product_card.html
{% load static %}

<style>
    li.catalog-item {
        background-color: #fff;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        margin: 10px;
        padding: 20px;
        width: 250px; /* Ajusta el ancho del elemento según tu preferencia */
        text-align: center;
        list-style-type: none;
    }

    img.catalog-image {
        max-width: 100%;
        max-height: 150px;
        border-radius: 8px;
        margin-bottom: 10px;
    }

    h2.catalog-title {
        color: #444aa0;
        font-size: 1.2em; /* Ajusta el tamaño de la fuente según tu preferencia */
    }

    p.catalog-description {
        color: #555;
        font-size: 0.9em; /* Ajusta el tamaño de la fuente según tu preferencia */
    }

    p.catalog-price {
        color: #333;
        font-size: 1.1em; /* Ajusta el tamaño de la fuente según tu preferencia */
    }

    a.catalog-link {
        display: inline-block;
        padding: 8px 16px;
        background-color: #343a40;
        color: #fff;
        text-decoration: none;
        border-radius: 4px;
        transition: background-color 0.3s ease;
        margin-top: 10px; /* Espacio entre el precio y el enlace */
    }

    a.catalog-link:hover {
        background-color: #000000;
    }
</style>


<li class="catalog-item">
    <h2 class="catalog-title">{{ product.name }}</h2>
    {% if product.image %}
        {%  include "product/out_of_stock.html" with base_path=product.image.url overlay_path="/static/img/out_of_stock.png" stock_amount=product.stock_amount%}
    {% else %}
        <img class="catalog-image" src="{% static 'placeholder-image.jpg' %}" alt="Placeholder Image">
    {% endif %}
    <p class="catalog-description">Stock: {{ product.stock_amount }}</p>

    <p class="catalog-price" style="font-size: 2em;">{{ product.price }} €</p>
    {% include "product/input_quantity_mini.html" with max=product.stock_amount %}
    <a class="catalog-link" href="{% url 'product_details' product.id %}">Ver detalles</a>
</li>